### PR TITLE
Extracted text formatter to separate service for consuming it in the components

### PR DESCRIPTION
**Pull request by romalytvynenko**
Helps to fix https://github.com/RebelCode/rcmod-wp-bookings-ui/issues/12

---
*Note:* these changes are made on top of the changes made in PR #17, branch `task/transitions-for-status-update`. The target merge branch for this PR has been set accordingly.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
I cannot understand the reason for the changes made in this PR, or what it actually achieves/fixes. I cannot see the relationship between these changes and RebelCode/rcmod-wp-bookings-ui#12.

**Comment by romalytvynenko** [comment]
In PR for https://github.com/RebelCode/rcmod-wp-bookings-ui/issues/12 I'm sending links to front-end.

In this PR I provide formatter to consume that links in templates.

**Comment by romalytvynenko** [comment]
Should I rename it?

**Comment by XedinUnknown** [comment]
Yes, please. A PR's title and description should describe the PR. Incidental effects on other code is not the concern of the PR. If it relates to other changes, PRs, or issues, such as in this case, then feel free to link to those.

**Pull request merged**
